from dataclasses import dataclass, field

@dataclass(frozen=True) 
# Makes Path objects immutable after creation
class Path:
    """
    Class for traversing Paths from Json documents and comparing.
    """
    # Internal storage for path segments
    # init=False means __init__ won't take this as an argument
    # repr=False means it won't be printed in the default __repr__
    _segments: tuple = field(init=False, repr=False, hash=True, compare=True) 
    
    # Cache for string representation
    # Not used for repr, comparison, or hashing as it's a derived, cached value
    _cached_string: str = field(init=False, repr=False, compare=False, hash=False)

    def __post_init__(self, path_string_or_segments):
        """
        This method is called automatically after __init__ is generated by dataclass
        It's used for any additional setup or validation 
        """
        segments_list = [] 
        # Use a list for initial processing

        if isinstance(path_string_or_segments, str):
            # If the input is a string, process it
            if not path_string_or_segments:
                # If the string is empty, it represents 'root' path, store it as an empty list of segments
                segments_list = [] 
            elif path_string_or_segments == "root":
                # If the string is explicitly "root", also treat it as the 'root' path
                # Store it as an empty list of segments.
                segments_list = []
            else:
                # For any other string, split it by the '.' delimiter to get the segments
                # Store the resulting list of segments.
                segments_list = path_string_or_segments.split('.')
        elif isinstance(path_string_or_segments, list):
            # If the input is already a list of segments, directly use it
            # Create a copy using list() to ensure the internal list is independent
            # of the input list, preventing external modifications
            segments_list = path_string_or_segments
        else:
            # If the input is neither a string nor a list, raise error
            raise ValueError("Path must be initialized with a string or list of segments.")
            
        # For frozen=True dataclasses, attributes set using object.__setattr__
        # Normal attribute assignment is prevented after __init__
        object.__setattr__(self, '_segments', tuple(segments_list)) 
        object.__setattr__(self, '_cached_string', None)

    def __str__(self):
        """
        This method defines how a Path object is converted to a string when str() is called on it.
        It uses a cached string representation for efficiency.
        """
        if self._cached_string is None:
            # For frozen dataclasses, using object.__setattr__ to avoid error
            if not self._segments:
                object.__setattr__(self, '_cached_string', "root")
            else:
                object.__setattr__(self, '_cached_string', ".".join(self._segments))
        # Return the cached string
        return self._cached_string

    # __eq__, __hash__, __len__, __getitem__ are automatically generated by @dataclass

    def segments(self):
        """
        This method returns a list of the path's segments.
        Returns a copy to prevent external modification of the internal tuple.
        """
        return list(self._segments)

    def parent(self):
        """
        This method returns a new Path object representing the parent path.
        """
        if not self._segments:
            # If the current path is the root, it has no parent, so return None
            return None 
        # Create a new Path object using all segments except the last one,
        # converting the tuple slice to a list for the Path constructor.
        return Path(list(self._segments[:-1]))

    def append(self, segment):
        """
        This method returns a new Path object with a new segment appended to the end.
        It creates a new list by concatenating the current segments with the new segment,
        and then uses this list to create a new Path object.
        """
        return Path(list(self._segments) + [segment])

    def is_root(self):
        """
        This method checks if the current Path object represents the 'root' path.
        Returns true if there are no segments.
        """
        return not self._segments

    def is_wildcard_segment(self, segment):
        """
        Helper method checks if a given segment string is the wildcard character '*'.
        """
        return segment == "*"

    # More to come